create table if not exists public.analyses (
  id bigint generated by default as identity primary key,
  kind text not null,
  input_hash text not null,
  input_preview text,
  result_json jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists analyses_created_at_idx on public.analyses (created_at desc);
create index if not exists analyses_kind_idx on public.analyses (kind);

alter table public.analyses enable row level security;

-- For server-side writes from Vercel, use SUPABASE_KEY as either the service-role
-- key or add a stricter policy for authenticated users. Do not expose service-role
-- keys in browser-side JavaScript.
